using Lexi;
var assertions = 0;
void Check(bool ok, string message) { assertions++; if (!ok) throw new Exception(message); }
var now = new DateTime(2026,10,10,12,0,0,DateTimeKind.Utc);
CanonicalHistoryRow Row(string word, string session, DateTime at, StudyRating rating = StudyRating.Known, CanonicalOrigin origin = CanonicalOrigin.FirstRetrieval) => new(word,session,origin,rating,at,at) { CanonicalId = "cr:" + word + ":" + session };
var empty = StudyStatistics.Build([], [], now, TimeZoneInfo.Utc);
Check(empty.LearningDays == 0 && empty.LearnedWords == 0 && empty.CardSeconds == 0, "empty history must stay empty");
var rows = new[] { Row("archive:a","1", now.AddDays(-2), origin:CanonicalOrigin.FirstLearnAggregate), Row("archive:a","2",now.AddDays(-1),StudyRating.Forgot), Row("archive:a","3",now), Row("ielts:a","4",now), Row("archive:a","3",now) };
var stats = StudyStatistics.Build(rows, [], now.AddSeconds(1), TimeZoneInfo.Utc);
Check(stats.LearnedWords == 2 && stats.Reviews == 3, "stable keys and canonical deduplication");
Check(stats.LearningDays == 3 && stats.LongestStreak == 3 && stats.CurrentStreak == 3, "streak uses real days");
Check(stats.PeakWords == 2, "daily vocabulary counts unique identities");
Check(stats.InsufficientWords.Single(w=>w.WordKey=="archive:a").Samples == 2, "acquisition must not inflate review sample");
var enough = rows.Append(Row("archive:a","5",now.AddHours(1),StudyRating.Forgot));
var ranked = StudyStatistics.Build(enough, [], now.AddHours(2), TimeZoneInfo.Utc);
Check(ranked.Forgettable.Single().Samples == 3 && Math.Abs(ranked.Forgettable.Single().Rate - 2d/3) < 1e-8, "30-day forgetting rate requires three reviews");
var old = StudyStatistics.Build(enough.Append(Row("archive:a","old",now.AddDays(-40),StudyRating.Forgot)),[],now.AddHours(2),TimeZoneInfo.Utc);
Check(old.Forgettable.Single().Samples == 3 && old.Forgettable.Single().AllForgotten == 3, "30 day and lifetime counts differ");
var lifetimeOnly=StudyStatistics.Build(new[]{Row("archive:old","old",now.AddDays(-50),StudyRating.Forgot)},[],now,TimeZoneInfo.Utc);
Check(lifetimeOnly.LifetimeForgettable.Single().AllForgotten==1&&lifetimeOnly.Forgettable.Count==0,"lifetime ranking includes words with no recent reviews");
var notCompleted=Row("archive:future","future",now.AddMinutes(-1)) with { CompletedAtUtc=now.AddMinutes(1) };
Check(StudyStatistics.Build(new[]{notCompleted},[],now,TimeZoneInfo.Utc).LearnedWords==0,"future completion excluded from finished facts");
var zone = TimeZoneInfo.CreateCustomTimeZone("test+8", TimeSpan.FromHours(8), "test+8", "test+8");
var midnight = new DateTime(2026,10,9,16,0,0,DateTimeKind.Utc);
var segments = new[] { new StudyActivity("s",StudyActivityKind.FirstLearn,midnight.AddSeconds(-30),midnight.AddSeconds(30),60), new StudyActivity("s",StudyActivityKind.Spelling,midnight.AddSeconds(30),midnight.AddSeconds(90),60) };
var zoned = StudyStatistics.Build([],segments,now,zone);
Check(zoned.Days[new DateOnly(2026,10,9)].FirstLearnSeconds==30 && zoned.Days[new DateOnly(2026,10,10)].FirstLearnSeconds==30, "split time at local midnight");
Check(zoned.SpellingSeconds==60 && zoned.CardSeconds==60 && zoned.LongestSessionSeconds==120,"separate activity kinds and same session");
var pixels = StudyStatistics.BuildGrid(zoned,2026,StatisticsPeriod.Cumulative,StatisticsActivityFilter.All);
Check(pixels.Count == 53 && pixels.Where(c=>!c.Future).Zip(pixels.Where(c=>!c.Future).Skip(1)).All(p=>p.First.Seconds<=p.Second.Seconds),"53 weekly cumulative columns are monotonic");
var weekly = StudyStatistics.BuildGrid(zoned,2026,StatisticsPeriod.Week,StatisticsActivityFilter.All);
Check(weekly.Count==53 && weekly.Sum(c=>c.Seconds)==120,"weekly grid does not double-count");
Check(pixels.Where(c=>c.Future).All(c=>c.Seconds==0),"future cumulative columns remain empty");
var cardOnly=StudyStatistics.BuildGrid(zoned,2026,StatisticsPeriod.Week,StatisticsActivityFilter.Cards);
Check(cardOnly.Sum(c=>c.Seconds)==60,"card filter excludes spelling duration");
var justYesterday=StudyStatistics.Build(new[]{Row("archive:a","yesterday",now.AddDays(-1))},[],now,TimeZoneInfo.Utc);
Check(justYesterday.CurrentStreak==1,"yesterday streak survives until today ends");
var stale=StudyStatistics.Build(new[]{Row("archive:a","stale",now.AddDays(-2))},[],now,TimeZoneInfo.Utc);
Check(stale.CurrentStreak==0,"missed calendar day ends current streak");
var month = StudyStatistics.BuildGrid(zoned,2026,StatisticsPeriod.Month,StatisticsActivityFilter.All);
Check(month.Count==53 && month.Where(c=>c.Start.Month==10&&!c.Future).All(c=>c.Seconds==120),"month grid repeats group height");
var leapEnd=new DateTime(2012,12,31,12,0,0,DateTimeKind.Utc);
var leapStats=StudyStatistics.Build([],new[]{new StudyActivity("leap",StudyActivityKind.Review,leapEnd,leapEnd.AddMinutes(1),60)},new DateTime(2013,1,1,12,0,0,DateTimeKind.Utc),TimeZoneInfo.Utc);
Check(StudyStatistics.BuildGrid(leapStats,2012,StatisticsPeriod.Week,StatisticsActivityFilter.All).Sum(c=>c.Seconds)==60,"Sunday-start leap years must include December 31");
var tracker = new StudyActivityTracker();
tracker.Advance(now,StudyActivityKind.Review,true,true);
tracker.Advance(now.AddSeconds(10),StudyActivityKind.Review,true,true);
tracker.Advance(now.AddSeconds(20),StudyActivityKind.Review,false,false);
Check(tracker.Drain().Sum(s=>s.Seconds)==10,"inactive or idle intervals do not count");
tracker.Advance(now.AddHours(1),StudyActivityKind.Review,true,true);
Check(tracker.Drain().Count==0,"sleep gaps must not count");
var mergedTracker=new StudyActivityTracker();
mergedTracker.Advance(now,StudyActivityKind.FirstLearn,true,true);
for(var second=1;second<=60;second++)mergedTracker.Advance(now.AddSeconds(second),StudyActivityKind.FirstLearn,true,true);
Check(mergedTracker.Drain().Count==1,"contiguous clock ticks must coalesce before persistence");
var kindTracker=new StudyActivityTracker();
kindTracker.Advance(now,StudyActivityKind.FirstLearn,true,true);kindTracker.Advance(now.AddSeconds(1),StudyActivityKind.FirstLearn,true,true);
kindTracker.Advance(now.AddSeconds(2),StudyActivityKind.Spelling,true,true);kindTracker.Advance(now.AddSeconds(3),StudyActivityKind.Spelling,true,true);
Check(kindTracker.Drain().Select(a=>a.SessionId).Distinct().Count()==2,"different activity kinds are distinct sessions");
var dir = Path.Combine(Path.GetTempPath(),"lexi-stat-tests-"+Guid.NewGuid().ToString("N")); Directory.CreateDirectory(dir);
try {
 var path = Path.Combine(dir,"activity.json"); var store = new StudyActivityStore(path);
 Check(store.Append(segments).Success && store.Read().Activities.Count==2,"atomic activity persistence");
 Check(store.Append(segments).Success && store.Read().Activities.Count==2,"retry is idempotent by activity identity");
 File.WriteAllText(path,"broken"); var recovery = store.Read();
 Check(recovery.Activities.Count==2 && recovery.Recovered && !recovery.Writable,"corrupt primary recovers backup and protects original");
 Check(!store.Append(segments).Success && File.ReadAllText(path)=="broken","failed reads cannot overwrite evidence");
 var blocked = new StudyActivityStore(dir); Check(!blocked.Append(segments).Success,"write errors are returned");
} finally { Directory.Delete(dir,true); }
Console.WriteLine($"Statistics tests passed: {assertions} assertions");
