#!/bin/bash
# Reproducible Apple Silicon installer. All mounts and temporary files belong to this run.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
APP_BUNDLE="$DIST_DIR/Lexi.app"
DMG_NAME="Lexi-3.1.1-macOS-arm64.dmg"
OUTPUT="$DIST_DIR/$DMG_NAME"
PYTHON_VENV="$ROOT_DIR/.tools/dmg-python/venv"
LAYOUT_SCRIPT="$ROOT_DIR/packaging/macOS/dmg-layout.py"
NO_BUILD=0

for arg in "$@"; do
    case "$arg" in
        --no-build) NO_BUILD=1 ;;
        --help|-h)
            echo "Usage: bash scripts/package_dmg.sh [--no-build]"
            echo "Default: build a self-contained osx-arm64 Lexi.app, then create and verify its DMG."
            echo "--no-build: package only the existing, verified dist/Lexi.app."
            exit 0 ;;
        *) echo "Unknown argument: $arg" >&2; exit 2 ;;
    esac
done

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "DMG packaging requires macOS / 安装包构建需要 macOS。" >&2
    exit 2
fi
if [[ "$NO_BUILD" == 0 ]]; then
    bash "$SCRIPT_DIR/package_app.sh" --rid=osx-arm64
fi

# 分发用的 DMG 同样必须是"被验收过的那一个 bundle"：否则 release.sh 之外存在一条无门禁发布通道。
python3 "$SCRIPT_DIR/release_proof.py" check --app "$APP_BUNDLE"

EXECUTABLE="$APP_BUNDLE/Contents/MacOS/Lexi"
[[ -x "$EXECUTABLE" ]] || { echo "Missing executable: $EXECUTABLE" >&2; exit 1; }
file "$EXECUTABLE" | /usr/bin/grep -q 'Mach-O' || { echo "Lexi must be a Mach-O executable." >&2; exit 1; }
[[ "$(/usr/bin/lipo -archs "$EXECUTABLE")" == "arm64" ]] || { echo "Expected the arm64 build; no Intel/Rosetta app will be packaged." >&2; exit 1; }
for required in Lexi.dll libhostfxr.dylib libcoreclr.dylib System.Private.CoreLib.dll Assets/dictionary.sqlite3; do
    [[ -f "$APP_BUNDLE/Contents/MacOS/$required" ]] || { echo "Self-contained app resource missing: $required" >&2; exit 1; }
done
/usr/bin/codesign --verify --deep --strict "$APP_BUNDLE"
python3 "$SCRIPT_DIR/stable_signing.py" verify "$APP_BUNDLE"
python3 "$SCRIPT_DIR/verify_release_privacy.py" "$APP_BUNDLE"
[[ "$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$APP_BUNDLE/Contents/Info.plist")" == "3.1.1" ]] || { echo "App version does not match DMG version 3.1.1." >&2; exit 1; }

# Install only into this project's isolated environment; never alter the user's global Python.
if [[ ! -x "$PYTHON_VENV/bin/python" ]]; then
    PYTHON_BIN="${LEXI_DMG_PYTHON:-$(command -v python3 || true)}"
    [[ -n "$PYTHON_BIN" ]] || { echo "Python 3.10+ is required only on the packaging Mac." >&2; exit 1; }
    "$PYTHON_BIN" -c 'import sys; assert sys.version_info >= (3, 10), "Python 3.10+ is required"'
    "$PYTHON_BIN" -m venv "$PYTHON_VENV"
fi
if ! "$PYTHON_VENV/bin/python" -c 'from importlib.metadata import version; assert version("ds-store") == "1.3.3" and version("mac-alias") == "2.2.3"' 2>/dev/null; then
    "$PYTHON_VENV/bin/python" -m pip install --disable-pip-version-check --no-deps 'ds-store==1.3.3' 'mac-alias==2.2.3'
fi

mkdir -p "$DIST_DIR"
WORK_DIR="$(mktemp -d "$DIST_DIR/.lexi-dmg-XXXXXX")"
MOUNT_DIR="$WORK_DIR/mount"
MOUNT_ACTIVE=0
LAYOUT_LOCK=""
cleanup() {
    local original_status=$?
    if [[ -n "$LAYOUT_LOCK" && -e "$LAYOUT_LOCK" ]]; then /usr/bin/chflags nouchg "$LAYOUT_LOCK" || true; fi
    if [[ "$MOUNT_ACTIVE" == 1 ]]; then
        if ! /usr/bin/hdiutil detach "$MOUNT_DIR"; then
            echo "Could not detach this run's mount. Preserved temporary directory: $WORK_DIR" >&2
            return "$original_status"
        fi
    fi
    if [[ "$original_status" != 0 ]]; then
        echo "Packaging failed; diagnostics preserved: $WORK_DIR" >&2
        return "$original_status"
    fi
    # WORK_DIR is generated by mktemp for this script; no user volumes or existing builds are removed.
    rm -rf "$WORK_DIR"
    return "$original_status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

STAGING="$WORK_DIR/volume"
mkdir -p "$STAGING" "$MOUNT_DIR"
/usr/bin/ditto "$APP_BUNDLE" "$STAGING/Lexi.app"
ln -s /Applications "$STAGING/Applications"
cat > "$STAGING/安装说明 · Install.txt" <<'GUIDE'
lexi · 安装 / Install

将 Lexi 拖入 Applications，推出此磁盘，再从“应用程序”打开 lexi。
Drag Lexi into Applications, eject this disk, then open lexi from Applications.

适用：Apple Silicon（M 系列芯片），macOS 12 或更新版本。
无需安装 .NET SDK；应用已包含运行环境与离线词典。
Requires Apple Silicon (M-series), macOS 12 or later.
No .NET SDK is needed; the runtime and offline dictionary are included.

在线 AI 功能需自行配置 API 地址、模型及 API Key；离线查词不需要网络或密钥。
Configure your own API endpoint, model and API Key for optional AI features.
Offline lookup works without a network connection or API Key.

跨应用选词：在本机“系统设置 → 隐私与安全性 → 辅助功能”授权 lexi。
For cross-app text selection, grant lexi Accessibility access on this Mac
in System Settings → Privacy & Security → Accessibility.
每台 Mac 必须自行授权；安装包不会携带他人的密钥或权限。
Each Mac grants its own permission; no personal keys or permissions are included.

此版本使用固定本机证书签名，未经过 Apple 公证。
首次打开若被 macOS 安全机制拦截，请确认文件来源可信，再按系统提示
进入“隐私与安全性”允许打开。请遵循本机系统提供的安全操作。
This build uses a persistent local signing certificate and has not been notarized by Apple.
If macOS blocks the first launch, confirm that you trust its source, then use
the system's Privacy & Security instructions to allow opening the app.

移除应用：退出 lexi，再将 Applications 中的 Lexi.app 移到废纸篓。
To remove the app, quit lexi and move Lexi.app from Applications to Trash.
GUIDE
"$PYTHON_VENV/bin/python" "$LAYOUT_SCRIPT" "$STAGING"
# Finder may rewrite staging metadata while observing the project directory.
LAYOUT_LOCK="$STAGING/.DS_Store"
/usr/bin/chflags uchg "$LAYOUT_LOCK"
python3 "$SCRIPT_DIR/verify_release_privacy.py" "$STAGING"

NEW_DMG="$WORK_DIR/$DMG_NAME"
REPORT="$WORK_DIR/validation.txt"
echo "Creating a compressed read-only UDZO image / 正在生成只读压缩安装包…"
/usr/bin/hdiutil create -volname 'lexi · Install' -srcfolder "$STAGING" -fs HFS+ -format UDZO -imagekey zlib-level=9 "$NEW_DMG"
{
    echo "Lexi 3.1.1 — Apple Silicon installer validation"
    /usr/bin/hdiutil verify "$NEW_DMG"
    /usr/bin/hdiutil imageinfo "$NEW_DMG" | /usr/bin/grep -E 'Format:|Class Name:|Checksum Type:|Size Information:' || true
} > "$REPORT" 2>&1

# Attach only this new image at our private path. Finder is never launched.
MOUNT_ACTIVE=1
/usr/bin/hdiutil attach "$NEW_DMG" -readonly -nobrowse -noautoopen -mountpoint "$MOUNT_DIR" -plist > "$WORK_DIR/attach.plist"
{
    echo "Mounted read-only contents:"
    ls -la "$MOUNT_DIR"
    [[ "$(readlink "$MOUNT_DIR/Applications")" == "/Applications" ]]
    echo "PASS Applications -> /Applications"
    [[ -s "$MOUNT_DIR/安装说明 · Install.txt" ]]
    [[ -f "$MOUNT_DIR/Lexi.app/Contents/Resources/Lexi.icns" ]]
    echo "PASS bilingual installation guide and approved app icon"
    file "$MOUNT_DIR/Lexi.app/Contents/MacOS/Lexi"
    [[ "$(/usr/bin/lipo -archs "$MOUNT_DIR/Lexi.app/Contents/MacOS/Lexi")" == "arm64" ]]
    /usr/bin/codesign --verify --deep --strict "$MOUNT_DIR/Lexi.app"
    echo "PASS mounted app strict code-signature verification"
    python3 "$SCRIPT_DIR/stable_signing.py" verify "$MOUNT_DIR/Lexi.app"
    # Audit the guide and Finder metadata as well as application contents.
    python3 "$SCRIPT_DIR/verify_release_privacy.py" "$MOUNT_DIR"
    SOURCE_HASH="$(/usr/bin/shasum -a 256 "$EXECUTABLE" | /usr/bin/awk '{print $1}')"
    MOUNTED_HASH="$(/usr/bin/shasum -a 256 "$MOUNT_DIR/Lexi.app/Contents/MacOS/Lexi" | /usr/bin/awk '{print $1}')"
    [[ "$SOURCE_HASH" == "$MOUNTED_HASH" ]]
    echo "PASS source and mounted arm64 executable SHA256 match: $SOURCE_HASH"
    SOURCE_ASSEMBLY_HASH="$(/usr/bin/shasum -a 256 "$APP_BUNDLE/Contents/MacOS/Lexi.dll" | /usr/bin/awk '{print $1}')"
    MOUNTED_ASSEMBLY_HASH="$(/usr/bin/shasum -a 256 "$MOUNT_DIR/Lexi.app/Contents/MacOS/Lexi.dll" | /usr/bin/awk '{print $1}')"
    [[ "$SOURCE_ASSEMBLY_HASH" == "$MOUNTED_ASSEMBLY_HASH" ]]
    echo "PASS source and mounted application assembly SHA256 match: $SOURCE_ASSEMBLY_HASH"
    "$PYTHON_VENV/bin/python" "$LAYOUT_SCRIPT" "$MOUNT_DIR" --verify
} >> "$REPORT" 2>&1
/usr/bin/hdiutil detach "$MOUNT_DIR"
MOUNT_ACTIVE=0
echo "PASS private verification volume detached" >> "$REPORT"

# Recoverable replacement; keep dist limited to the current deliverables.
for suffix in '' .sha256 .validation.txt; do
    if [[ -e "$OUTPUT$suffix" ]]; then
        /usr/bin/swift "$SCRIPT_DIR/trash_generated.swift" "$OUTPUT$suffix"
    fi
done
mv "$NEW_DMG" "$OUTPUT"
cp "$REPORT" "$OUTPUT.validation.txt"
(cd "$DIST_DIR" && /usr/bin/shasum -a 256 "$DMG_NAME" > "$DMG_NAME.sha256")
cat "$OUTPUT.validation.txt"
cat "$OUTPUT.sha256"
echo "Ready to share / 可发送给其他 M 系列 Mac：$OUTPUT"
