from pathlib import Path
import json
r=Path(__file__).parent
quote=lambda s: json.dumps(s,ensure_ascii=False)
a=json.loads((r/'strings.json').read_text());b=json.loads((r/'static-resources.json').read_text())
content='''// Generated by Localization/generate.py from checked-in JSON dictionaries.
namespace Lexi;

internal static class UiCatalog
{
    internal static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
'''
content+=''.join('        ['+quote(k)+'] = '+quote(v)+',\n' for k,v in a.items())
content+='    };\n    internal static readonly Dictionary<string, string> Resources = new(StringComparer.Ordinal)\n    {\n'
content+=''.join('        ['+quote(k)+'] = '+quote(v)+',\n' for k,v in b.items());content+='    };\n}\n'
(r/'UiCatalog.cs').write_text(content)
